$color = rgba(242, 229, 188, 1)
$inner_color = rgba(242, 229, 188, 0.66)
$outer_color = rgba(177, 98, 134, 1)
$font_color = rgba(60, 56, 54, 1)
$placeholder_color = rgba(60, 56, 54, 0.7)
$check_color = rgba(104, 157, 106, 1)
